### ISSUE TITLE
Could a new v1.5 release get tagged?

### ISSUE THREAD

**Issue by ecaron** [neitanod/forceutf8#42]
There's a lot of fantastic work happening and I love seeing so much activity. But having a newer tag release would help me feel more comfortable with my build stability.

**Comment by j0k3r** [comment]
I agree.

**Comment by emilioastarita** [comment]
+1 for this.

**Comment by JavierCane** [comment]
+1!

It would be great to follow [Semantic Versioning](http://semver.org/)

**Comment by saber3005** [comment]
+1

Having to rely on dev-master means that I can't take advantage of composer caching =(

**Comment by JustinCarmony** [comment]
+1

I always get nervous pointing to dev-master in composer.

**Comment by byjg** [comment]
yeah, me too

**Comment by dominikzogg** [comment]
+1

**Comment by kreed-rmn** [comment]
+1

**Comment by neitanod** [comment]
Done.

Those using a reference to "dev-master" can now safely refer to "2.0".

Those that are still using "v1.4" (because "dev-master" didn't work in some PHP envrionments) can safely refer to "v1.5".  

The v1 branch and it's tags will always be compatible with any PHP environment, at the expense of not using "iconv" and thus missing some special cases.

**Comment by byjg** [comment]
Thank you!! I tried to use on packagist but it seems does not updated automatically. I believe you have to update manually on packagist. 
![neitanod forceutf8 packagist](https://cloud.githubusercontent.com/assets/981924/9828939/e76c8476-58cb-11e5-802d-1c8d296bb93d.png)
