### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by byjg** [neitanod/forceutf8#44]
Hi, this project is very useful for the community and there are a lot of suggestions and requests but there is no answers from the maintainers. Is this project still alive?

**Comment by neitanod** [comment]
Yes, the project is still alive, it's just that it's stable enough to require little or no changes at this point.

Most of the issues are opened because users dont quite understand how encoding conversion -and encodign itself- really works, and they just want some particular character magically detected in the process.  I sometimes respond to those requests with private messages.

The only real issue I am delaying an answer to is the request for a new stable tag.  There are some tests that could help find any error, but the difficult part is to keep all the needed environments to run the tests on, because some errors arise from different versions of PHP or the absence of an extension, or the included configuration for the inclusion mechanism for Composer.

I guess i will just tag the current version and let users report any problem.  In fact there are no current valid bug reports open.

**Comment by byjg** [comment]
Really thank you for answer me. I like your work and use your code. In fact my motivation for open this issue is about the tag. Note that there are no newer commits since may so you could tag the code with "1.5.0" . If there some changes you can tag the new commits with 1.5.1, 1.5.2 and so on. For me, the code is pretty stable.
