### ISSUE TITLE
japanese characters are turned to ?

### ISSUE THREAD

**Issue by gerald27** [neitanod/forceutf8#50]
Hi,

I'm using your library and it works but I only have one problem when I enter chinese or japanese characters it converted to "?". Any solution for this?

Thanks

**Comment by peter-p2people** [comment]
Hi,

I have the same problem. The library solves my encoding problems with Latin-based languages, but when it encounters Asian script, it outputs "???". Is there a fix to recognize these UTF-8 characters?

Thanks,

**Comment by neitanod** [comment]
Are you using toUTF() or fixUTF8() ?

**Comment by neitanod** [comment]
As I said in another open issue, I should probably remove fixUFT8() from this package, because as the documentation says, it's not intended for a production environment.
I did it to fix a set of broken files that I was able to check afterwards. It's useful if your text has occidental characters only, but will break things in other cases, so It's not really supposed to be left runing unattended on any input that may come.
