### ISSUE TITLE
fixUTF8 Problem with certain characters

### ISSUE THREAD

**Issue by cruvalcaba** [neitanod/forceutf8#7]
Hi, I have found that the fixUTF8 has issues when the input string has ligature characters such as Œ, this is converted to a ? sign, even tough the input string does not need any fixing.

Input: Café Nöel Œuf Aoüt
Output: Café Nöel ?uf Août

**Comment by jonascarlbaum** [comment]
Hi,
your fixUTF8 method works great in most cases, I was about to use it in a bulk job, but I had to stop using it since it messed up some standard characters, as such as ```—``` (em-dash) and didn't fix swedish uppercase characters..

Consider the following PHPUnit assertion:

    $this->assertEquals(
            "ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäöÅÄÖåäö-_—.,:;'\"\\/?={}[]()<>&%\$¤#£@!§½*^¨~",
        \ForceUTF8\Encoding::fixUTF8(
            "ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäöÃ…Ã„Ã–Ã¥Ã¤Ã¶-_—.,:;'\"\\/?={}[]()<>&%\$¤#£@!§½*^¨~"
        )
    );

Which generates the following output:
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäöÅÄÖåäö-_—.,:;'"\/?={}[]()<>&%$¤#£@!§½*^¨~'
> +'ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäöÃ?Ã?Ã?åäö-_?.,:;'"\/?={}[]()<>&%$¤#£@!§½*^¨~'

So it won't fix ```Ã…Ã„Ã–``` => ```ÅÄÖ``` or keep ```—``` (em-dash), but fixes ```Ã¥Ã¤Ã¶``` => ```åäö``` and keep ```-``` and other standard characters as is.
The ```ÅÄÖ``` is obviously the upper characters of ```åäö``` and  is very common and important in swedish language. And I think that ```—``` (em-dash) should be preserved as is.

I think it would be great if fixUTF8 passed this assertion. :thumbsup:

**Comment by neitanod** [comment]
Are you converting from ISO-8859-1/Win1252 or some other ISO encoding?

**Comment by jonascarlbaum** [comment]
> Are you converting from ISO-8859-1/Win1252 or some other ISO encoding?

Well, we are receiving corrupt data from emails, using third-party software (Email2DB) to store it in our DB. Using MySql and UTF-8. It most probably is ISO-8859-1/Win1252 encoded but sent as a multipart email where the encoding is said to be UTF-8 but the text content that gets parsed is not UTF-8. 

However, we get the wrong data and have no control over how it. So we have to clean up the mess if we don't mess up something else... ;)

If you run ```mb_convert_encoding("ÅÄÖåäö—", 'UTF-8', 'Windows-1252')``` you get the characters I identified, so Windows-1252 seems to be the encoding.

**Comment by neitanod** [comment]
Have you tried the alternatives?
\ForceUTF8\Encoding::fixUTF8($srting, \ForceUTF8\Encoding::WITHOUT_ICONV);  //default
\ForceUTF8\Encoding::fixUTF8($srting, \ForceUTF8\Encoding::ICONV_TRANSLIT);
\ForceUTF8\Encoding::fixUTF8($srting, \ForceUTF8\Encoding::ICONV_IGNORE);

**Comment by jonascarlbaum** [comment]
Well, no, and ```\ForceUTF8\Encoding::ICONV_TRANSLIT``` and ```\ForceUTF8\Encoding::ICONV_IGNORE``` both did the trick.

However, will that break stuff if already correct UTF-8?
What is the difference in the three alternatives, in short words? ;)

**Comment by neitanod** [comment]
The original version (now v1 branch) of this library used the PHP native utf8_decode() at some points.  It worked well when converting from "real" Latin1 (mixed with "UTF8-already" chunks) to well formed UTF8.

Then I added support for Win1252, which is supported by most applications that accept Latin1.  In fact, those apps (browsers included) say they use Latin1 when they are in fact using Win1252 (which has the Euro sign among other additions).

But the PHP native utf8_decode() function which I am internally using accepts "real" Latin1 only, not Win1252, and while toUTF8() was working fine, FixUTF8() breaks the Euro sign.

The solution for that is to ditch utf8_decode() and use the iconv library instead, but it's not always installed, and it has it's own issues, so I chose to take the backwards compatible path and use utf8_decode() by default, while allowing to use iconv also.

Will it break your output?  

toUTF8() will not break, but it has it's expected failure cases (see the comments of the function in the source code) because detecting the encoding of an incoming string is plain impossible.  The library is  just making assumptions:  Input is assumed to be UTF8 and if it's *obviously not* it will be treated as Win1252.
But sometimes it really *is* Win1252, but those character sequence are also valid UTF8.  It falls into the category where input is not *obviously not* UTF8, and passes without conversion.

Will fixUTF8() break?

Well, this function is just a tool to keep at hand.  It works, but it's slow and you should not use it in production, as I said many times before.  Use it, have a look at the output, and then approve or dissaprove.

Not using iconv is already breaking it for sure, as you have seen.

Using iconv: It will break in less opportunities, it does a better job than the default version, but it depends on the iconv library guys and I can't garantee if will not break, and in case it does, I don't think that I could do much to fix it.

But more importantly thing is that if your data includes characters that do not exist in Latin1 (let's say russian or chinese characters), your "fixed UTF8", they would be transliterated or ommited, so beware.

**Comment by neitanod** [comment]
I just re read your question...  I missed the "in short words" part earlier, sorry, he.
Well, the words themselves are short, there are just a lot of them.
![potato](http://www.foodsubs.com/Photos/potatoes-whitelong.jpg)

**Comment by david4worx** [comment]
One could also try to use http://php.net/manual/en/uconverter.transcode.php or any of the other [Intl ](http://nl1.php.net/intl)classes->methods
