### ISSUE TITLE
utf symbols converted to questionmarks

### ISSUE THREAD

**Issue by kgiedrius** [neitanod/forceutf8#71]
I try to use utf fixer with Lithuanian characters like: čęėįšųūž
and they are being replaced with questionmarks :(

**Ex. ForceUTF8\Encoding::fixUTF8('Kėbulo numeris')
Result: K?ebulo numeris**

Same with other mensioned letters.

**Comment by garrettw** [comment]
[As the readme mentions](https://github.com/neitanod/forceutf8#description), this library currently only supports ISO-8859-1 or Windows 1252 as input.

**Comment by kgiedrius** [comment]
Are there any plans to support extend library ?

**Comment by garrettw** [comment]
I am not aware of any plans.

**Comment by chrisharrisonkiwi** [comment]
Dang, this is a deal breaker. Otherwise great tool!

**Comment by neitanod** [comment]
Be aware that fixUTF8 function is only intended to fix double encoded strings.  Those are strings that were "converted" to UTF8 without realizing that they already were UTF8 encoded, resulting in characters as "Ã©" taking the place of "é".

fixUTF8 is not really intended to be used in a production environment, because it would break cases where you actually want to show the characters "Ã©", like, for example, this answer.
It was developed as a tool to manually repair large texts before sending them as input to a fully UTF8 environment that wouldn't generate new broken strings.

Having said that, you can try the variations to see if they fit your needs at least partially:
`\ForceUTF8\Encoding::fixUTF8($str, ForceUTF8\Encoding::ICONV_IGNORE);`
or
`\ForceUTF8\Encoding::fixUTF8($str, ForceUTF8\Encoding::ICONV_TRANSLIT);`

None of those will keep characters not present in ISO-8859-1 or WIN1252 charset but at least they won't break that awfully.  The first one will remove them completely and the second one will transliterate them to a close relative ("čęėįšųūž" -> "ceeišuuž").

The transliteration is provided by the ICONV library, so I cannot make adjustments to it.
